#!/usr/bin/python

# pysendmail
# author: Ondrej Sika, http://ondrejsika.com, ondrej@ondrejsika.com
# licence: MIT

import argparse

from libpysendmail import sendmail


parser = argparse.ArgumentParser()
parser.add_argument("-f", "--fromemail", help="from email", required=True)
parser.add_argument("-t", "--toemail", help="to email", required=True)
parser.add_argument("-m", "--message", help="message", required=True)

parser.add_argument("-u", "--user", help="user", required=True)
parser.add_argument("-p", "--password", help="password", required=True)
parser.add_argument("-s", "--server", help="server:port", required=True)


if __name__ == "__main__":
    args = parser.parse_args()
    sendmail(
        args.fromemail,
        args.toemail,
        args.message,
        args.user,
        args.password,
        args.server,
    )