#!/usr/bin/python

# pysendmail
# author: Ondrej Sika, http://ondrejsika.com, ondrej@ondrejsika.com
# licence: MIT

import argparse

from libpysendmail import sendmail


parser = argparse.ArgumentParser()
parser.add_argument('-f', help='from email', required=True)
parser.add_argument('-t', help='to email', required=True)
parser.add_argument('-m', help='message', required=True)

parser.add_argument('-u', help='user', required=True)
parser.add_argument('-p', help='password', required=True)
parser.add_argument('-s', help='server:port', required=True)


if __name__ == '__main__':
    args = parser.parse_args()
    sendmail(
        args.f,
        args.t,
        args.m,
        args.u,
        args.p,
        args.s,
    )